apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-subscriber-deployment
  # namespace: thalla
  labels:
    app: mqtt-subscriber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-subscriber
  template:
    metadata:
      labels:
        app: mqtt-subscriber
    spec:
      containers:
      - name: mqtt-subscriber
        image: thalla22/mqtt-subscriber-arm
        env:
        - name: BROKER_ADDRESS
          value: mqtt-broker-clusterip-service.default
        - name: BROKER_PORT
          value: "1883"
        # - name: DATA_TOPIC_AUTHOR
        #   value: "Thalla"
        - name: Temperature_Threshold
          value: "30.0"
        - name: Humidity_Threshold
          value: "70.0"
