apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-broker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-broker
  template:
    metadata:
      labels:
        app: mqtt-broker
    spec:
      containers:
      - name: mqtt-broker
        image: thalla22/mosquitto_broker_arm
        ports:
        - containerPort: 1883
---
apiVersion: v1
kind: Service
metadata:
  name: mqtt-broker-service
spec:
  type: NodePort
  selector:
    app: mqtt-broker
  ports:
  - name: mqtt
    port: 1883
    targetPort: 1883
    nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: mqtt-broker-clusterip-service
spec:
  selector:
    app: mqtt-broker
  ports:
  - name: mqtt
    port: 1883
    targetPort: 1883
    protocol: TCP
  type: ClusterIP
