---
- hosts: all
  gather_facts: false

  tasks:

    # - name: Make the location
    #   file:
    #     path: /tmp/playing-opera/hello
    #     recurse: true
    #     state: directory
    - name: download k3s agent on worker node & join it to k3s cluster
      shell: "curl -sfL https://get.k3s.io | K3S_URL={{ apiserver_url }} K3S_TOKEN={{ k3s_worker_token }} sh - "