---
- hosts: all
  gather_facts: false
  tasks: 
     
    # - name: Remove the location
    #   file:
    #     path: /tmp/playing-opera
    #     state: absent
    - name: Uninstalling k3s agent on workers
      shell: "/usr/local/bin/k3s-agent-uninstall.sh"